CREATE TABLE IF NOT EXISTS `RFSA`.`SEGMENTATION_LIST` (
  `SEG_ID` VARCHAR(25) NOT NULL,
  `SEG_TYPE` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`SEG_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RFSA`.`INDIVIDUAL_SEGMENT_MASTER` (
  `IND_SEG_ID` VARCHAR(25) NOT NULL,
  `IND_SEG_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`IND_SEG_ID`),
  INDEX `fk_INDIVIDUAL_SEGMENT_MASTER_SEGMENTATION_LIST_idx` (`IND_SEG_ID` ASC),
  CONSTRAINT `fk_INDIVIDUAL_SEGMENT_MASTER_SEGMENTATION_LIST`
    FOREIGN KEY (`IND_SEG_ID`)
    REFERENCES `RFSA`.`SEGMENTATION_LIST` (`SEG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RFSA`.`GROUP_SEGMENT_MASTER` (
  `GRP_SEG_ID` VARCHAR(25) NOT NULL,
  `GRP_SEG_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`GRP_SEG_ID`),
  INDEX `fk_GROUP_SEGMENT_MASTER_SEGMENTATION_LIST1_idx` (`GRP_SEG_ID` ASC),
  CONSTRAINT `fk_GROUP_SEGMENT_MASTER_SEGMENTATION_LIST1`
    FOREIGN KEY (`GRP_SEG_ID`)
    REFERENCES `RFSA`.`SEGMENTATION_LIST` (`SEG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RFSA`.`ROOM_ACTUAL` (
  `ACTUAL_ID` VARCHAR(20) NOT NULL,
  `SEG_ID` VARCHAR(25) NOT NULL,
  `DATE` DATE NULL,
  `BUDGET_RNS` DOUBLE NULL,
  `BUDGET_ARR` DOUBLE NULL,
  `BUDGET_REVENUE` DOUBLE NULL,
  `ACTUAL_RNS` DOUBLE NULL,
  `ACTUAL_ARR` DOUBLE NULL,
  `ACTUAL_REVENUE` DOUBLE NULL,
  PRIMARY KEY (`ACTUAL_ID`, `SEG_ID`),
  INDEX `fk_ROOM_ACTUAL_SEGMENTATION_LIST1_idx` (`SEG_ID` ASC),
  CONSTRAINT `fk_ROOM_ACTUAL_SEGMENTATION_LIST1`
    FOREIGN KEY (`SEG_ID`)
    REFERENCES `RFSA`.`SEGMENTATION_LIST` (`SEG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RFSA`.`ROOM_FORECAST` (
  `FORECAST_ID` VARCHAR(20) NOT NULL,
  `SEG_ID` VARCHAR(25) NOT NULL,
  `DATE` DATE NOT NULL,
  `FORECAST_RNS` DOUBLE NOT NULL,
  `FORECAST_ARR` DOUBLE NOT NULL,
  `FORECAST_REVENUE` DOUBLE NOT NULL,
  PRIMARY KEY (`FORECAST_ID`, `SEG_ID`),
  INDEX `fk_ROOM_FORECAST_SEGMENTATION_LIST1_idx` (`SEG_ID` ASC),
  CONSTRAINT `fk_ROOM_FORECAST_SEGMENTATION_LIST1`
    FOREIGN KEY (`SEG_ID`)
    REFERENCES `RFSA`.`SEGMENTATION_LIST` (`SEG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RFSA`.`FORECAST_USES_ACTUAL` (
  `ACTUAL_ID` VARCHAR(20) NOT NULL,
  `FORECAST_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ACTUAL_ID`, `FORECAST_ID`),
  INDEX `fk_ROOM_ACTUAL_has_ROOM_FORECAST_ROOM_FORECAST1_idx` (`FORECAST_ID` ASC),
  INDEX `fk_ROOM_ACTUAL_has_ROOM_FORECAST_ROOM_ACTUAL1_idx` (`ACTUAL_ID` ASC),
  CONSTRAINT `fk_ROOM_ACTUAL_has_ROOM_FORECAST_ROOM_ACTUAL1`
    FOREIGN KEY (`ACTUAL_ID`)
    REFERENCES `RFSA`.`ROOM_ACTUAL` (`ACTUAL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROOM_ACTUAL_has_ROOM_FORECAST_ROOM_FORECAST1`
    FOREIGN KEY (`FORECAST_ID`)
    REFERENCES `RFSA`.`ROOM_FORECAST` (`FORECAST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB